name: uranus

env:
  TAG: v0.2.0

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install and build
        run: |
          yarn install
          yarn build
        env:
          CI: false
      - name: Login to GitHub Package Registry
        run: docker login docker.pkg.github.com -u owner -p ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag docker.pkg.github.com/project-uranus/uranus-web/uranus-web:${TAG}
      - name: Push the image to GitHub Package Registry
        run: docker push docker.pkg.github.com/project-uranus/uranus-web/uranus-web:${TAG}
